### ISSUE TITLE
POSSE: Mastodon

### ISSUE THREAD

**Issue by mro** [mro/ShaarliGo#17]
https://www.hyperborea.org/journal/2017/12/mastodon-ifttt/

**Comment by mro** [comment]
1. manually create an app at https://social.tchncs.de/settings/applications – just permission `write:statuses` is enough,
2. add another entry in `posse:` of `app/config.yaml` like
```yaml
- mastodon: https://social.tchncs.de/
  token: aigoh3eeleeb2QuaM7…
  prefix: 
```
